version: '3'
services:
    web:
        image: loupeznik/better-wapi-webapp:1.3.0
        ports:
            - 8084:80
        volumes:
            - ./public/config.json:/usr/share/nginx/html/config.json
        restart: unless-stopped
        container_name: bwapi-webapp
    api:
        image: loupeznik/better-wapi:1.2.0
        ports:
            - 8083:8000
        env_file:
            - .env
        restart: unless-stopped
        container_name: bwapi
